name: Docker Image CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Build the Docker image on runner


    - name: display current branch
      run : echo ${GITHUB_HEAD_REF}
   # - name: Build the Docker image 
     # run: docker build . --file Dockerfile --tag python-app:${{ github.run_number }}

    # Login to Docker hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
# Tag Docker Image 
    - name: Tag the docker image
      run: docker build . --file Dockerfile --tag mrmayanger/python-flask:v1.${{ github.run_number }}
# Push docker image to Dockerhub
    - name: Push the docker image
      run: docker push  mrmayanger/python-flask:v1.${{ github.run_number }}