name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-app:$(date +%s)

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag the docker image
      run: docker tag python-app:$(date +%s) mrmayanger/python-flask:v1.$(date +%s)

    - name: Push the docker image
      run: docker push  mrmayanger/python-flask:v1.$(date +%s)